export {
  CONSOLE_ADDON_API_VERSION,
  consoleCapabilities,
  consoleExtensionPoints,
  consoleServices,
  createConsoleAddonManager,
  createConsoleCapability,
  createConsoleCapabilityRegistry,
  createConsoleDisposableScope,
  createConsoleExtensionPoint,
  createConsoleExtensionRegistry,
  createConsoleServiceRegistry,
  createConsoleServiceToken,
} from "@moyarich/console-core";
export type {
  ConsoleAddon,
  ConsoleAddonCleanup,
  ConsoleAddonHost,
  ConsoleAddonManager,
  ConsoleCapability,
  ConsoleCapabilityRegistry,
  ConsoleDisposable,
  ConsoleDisposableScope,
  ConsoleExtensionPoint,
  ConsoleExtensionRegistrationOptions,
  ConsoleExtensionRegistry,
  ConsoleFrameDecorator,
  ConsoleFrameDecoratorContext,
  ConsoleMessageDecoration,
  ConsoleMessageDecorationContext,
  ConsoleMessageDecorationPlacement,
  ConsoleMessageFilter,
  ConsolePanelElement,
  ConsolePanelElementContext,
  ConsolePanelElementPlacement,
  ConsoleServiceRegistry,
  ConsoleServiceToken,
  CreateConsoleAddonManagerOptions,
} from "@moyarich/console-core";
